//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEnvironmentSnapshots.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankProject
    {
        public string CountryCode { get; set; }
        public string ProjectId { get; set; }
        public string ProjectName { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string ProjectType { get; set; }
        public string ProjectLink { get; set; }
        public string ProjectStatus { get; set; }
    }
}
