//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEnvironmentSnapshots.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int CountryId { get; set; }
        public string CountryCode { get; set; }
        public string CountryName { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> IncomeId { get; set; }
        public Nullable<int> LowIncomeRegionId { get; set; }
        public Nullable<int> EconomicalRegionId { get; set; }
        public string CountryAlias { get; set; }
        public bool Visible { get; set; }
    }
}
